blank_issues_enabled: false
contact_links:
  - name: Security Issues
    url: https://github.com/brktrl/django-remix-icon/security/policy
    about: Please report security issues through our security policy.
  - name: Questions & Discussions
    url: https://github.com/brktrl/django-remix-icon/discussions
    about: Please ask and answer questions here.
